MACOS_THEMES = {
    "macOS Light": {
        "primary": "#0071e3",
        "background": "#f5f5f7",
        "secondary_background": "#ffffff",
        "text": "#1d1d1f",
        "border": "#d2d2d7",
        "foreground": "#1d1d1f",
        "card": "#ffffff",
        "card_foreground": "#1d1d1f",
        "popover": "#ffffff",
        "popover_foreground": "#1d1d1f",
        "primary_foreground": "#ffffff",
        "secondary": "#e5e5ea",
        "secondary_foreground": "#1d1d1f",
        "muted": "#f5f5f7",
        "muted_foreground": "#86868b",
        "accent": "#0071e3",
        "accent_foreground": "#ffffff",
        "destructive": "#ff3b30",
        "destructive_foreground": "#ffffff",
        "input": "#ffffff",
        "ring": "#0071e3",
        "sidebar": "#f5f5f7",
        "sidebar_foreground": "#1d1d1f",
        "sidebar_primary": "#0071e3",
        "sidebar_primary_foreground": "#ffffff",
        "sidebar_accent": "#e5e5ea",
        "sidebar_accent_foreground": "#0071e3",
        "sidebar_border": "#d2d2d7",
        "sidebar_ring": "#0071e3",
        "font_sans": "-apple-system, BlinkMacSystemFont, 'SF Pro Display', 'SF Pro Text', 'Segoe UI', Roboto, sans-serif",
        "font_mono": "SFMono-Regular, Consolas, Menlo, Monaco, monospace",
        "radius": "10px",
        "border_width": "1px",
        "shadow_2xs": "0 1px 2px rgba(0, 0, 0, 0.05)",
        "shadow_xs": "0 1px 2px rgba(0, 0, 0, 0.05)",
        "shadow_sm": "0 2px 8px rgba(0, 0, 0, 0.04)",
        "shadow": "0 4px 12px rgba(0, 0, 0, 0.05)",
        "shadow_md": "0 8px 24px rgba(0, 0, 0, 0.08)",
        "shadow_lg": "0 12px 30px rgba(0, 0, 0, 0.1)",
        "shadow_xl": "0 20px 40px rgba(0, 0, 0, 0.12)",
        "shadow_2xl": "0 25px 50px rgba(0, 0, 0, 0.15)",
    },
    "macOS Dark": {
        "primary": "#0a84ff",
        "background": "#1e1e1e",
        "secondary_background": "#2c2c2e",
        "text": "#f5f5f7",
        "border": "#3a3a3c",
        "foreground": "#f5f5f7",
        "card": "#2c2c2e",
        "card_foreground": "#f5f5f7",
        "popover": "#2c2c2e",
        "popover_foreground": "#f5f5f7",
        "primary_foreground": "#ffffff",
        "secondary": "#3a3a3c",
        "secondary_foreground": "#f5f5f7",
        "muted": "#1e1e1e",
        "muted_foreground": "#86868b",
        "accent": "#0a84ff",
        "accent_foreground": "#ffffff",
        "destructive": "#ff453a",
        "destructive_foreground": "#ffffff",
        "input": "#2c2c2e",
        "ring": "#0a84ff",
        "sidebar": "#1e1e1e",
        "sidebar_foreground": "#f5f5f7",
        "sidebar_primary": "#0a84ff",
        "sidebar_primary_foreground": "#ffffff",
        "sidebar_accent": "#3a3a3c",
        "sidebar_accent_foreground": "#0a84ff",
        "sidebar_border": "#3a3a3c",
        "sidebar_ring": "#0a84ff",
        "font_sans": "-apple-system, BlinkMacSystemFont, 'SF Pro Display', 'SF Pro Text', 'Segoe UI', Roboto, sans-serif",
        "font_mono": "SFMono-Regular, Consolas, Menlo, Monaco, monospace",
        "radius": "10px",
        "border_width": "1px",
        "shadow_2xs": "0 1px 2px rgba(0, 0, 0, 0.15)",
        "shadow_xs": "0 1px 2px rgba(0, 0, 0, 0.15)",
        "shadow_sm": "0 2px 8px rgba(0, 0, 0, 0.12)",
        "shadow": "0 4px 12px rgba(0, 0, 0, 0.15)",
        "shadow_md": "0 8px 24px rgba(0, 0, 0, 0.18)",
        "shadow_lg": "0 12px 30px rgba(0, 0, 0, 0.22)",
        "shadow_xl": "0 20px 40px rgba(0, 0, 0, 0.25)",
        "shadow_2xl": "0 25px 50px rgba(0, 0, 0, 0.3)",
    }
}
